"""Semantic models for scopes, symbols, types, and later analysis passes."""

from c_analyzer.semantic.analyzer import SemanticAnalyzer, SemanticResult, analyze
from c_analyzer.semantic.model import SemanticModel
from c_analyzer.semantic.intellisense import (
    CompletionEngine,
    CompletionItem,
    DefinitionLocation,
    HoverInfo,
    complete,
    hover,
    position_from_line_column,
)
from c_analyzer.semantic.scope_builder import (
    SymbolTableBuilder,
    SymbolTableResult,
    build_symbol_table,
)
from c_analyzer.semantic.type_checker import TypeChecker, check_types
from c_analyzer.semantic.symbols import (
    AccessKind,
    Reference,
    Scope,
    ScopeKind,
    Symbol,
    SymbolKind,
    SymbolNamespace,
    render_scope_tree,
)
from c_analyzer.semantic.types import (
    ArrayType,
    CHAR,
    CType,
    DOUBLE,
    ERROR,
    ErrorType,
    FLOAT,
    FunctionType,
    INT,
    PointerType,
    PrimitiveType,
    StructType,
    UNKNOWN,
    UnknownType,
    VOID,
    primitive_type,
)

__all__ = [
    "AccessKind",
    "ArrayType",
    "CHAR",
    "CType",
    "CompletionEngine",
    "CompletionItem",
    "DOUBLE",
    "ERROR",
    "ErrorType",
    "FLOAT",
    "FunctionType",
    "DefinitionLocation",
    "HoverInfo",
    "INT",
    "PointerType",
    "PrimitiveType",
    "Reference",
    "Scope",
    "ScopeKind",
    "SemanticAnalyzer",
    "SemanticModel",
    "SemanticResult",
    "StructType",
    "Symbol",
    "SymbolKind",
    "SymbolNamespace",
    "SymbolTableBuilder",
    "SymbolTableResult",
    "TypeChecker",
    "UNKNOWN",
    "UnknownType",
    "VOID",
    "analyze",
    "build_symbol_table",
    "check_types",
    "complete",
    "hover",
    "position_from_line_column",
    "primitive_type",
    "render_scope_tree",
]
